" - Vimrc -

" Syntax Highlighting
syntax on
filetype plugin on
filetype plugin indent on

set wildmenu " display all mathcing files when we tab complete
set path+=** " search down into subfolders
set nocompatible " enter the current millenium
set number
set laststatus=2 " Status Bar
set backspace=indent,eol,start "Backspacing all the way 
set mouse=n

" Indenting
set expandtab
set autoindent
set smartindent

" Color correction Tmux 
colorscheme slate
hi Comment ctermfg=34


" Use jj as escape key
inoremap jj <Esc> " Remap ESC to jk

