" - Vimrc -


" ---- Plugins ---- "
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
"Plug 'jiangmiao/auto-pairs'
Plug 'preservim/nerdtree'
"Plug 'preservim/nerdcommenter'
call plug#end()

" Syntax Highlighting
syntax enable 
filetype plugin on
filetype plugin indent on

set wildmenu " display all mathcing files when we tab complete
set path+=** " search down into subfolders
set nocompatible " enter the current millenium
set number " Relative Line Numbers
set laststatus=2 " Status Bar
set ruler
set backspace=indent,eol,start "Backspacing all the way 
set mouse=a

" Indenting
set expandtab
set autoindent
set smartindent

"NerdTree"
nmap <F6> :NERDTreeToggle<CR>

" Use jj as escape key
inoremap jj <Esc> " Remap ESC to jk

" ---- Coc ----- "
" Use tab for trigger completion with characters ahead and navigate.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
